background_b: 255
background_g: 86
background_r: 150
rosdistro: 'kinetic

  '
roslaunch:
  uris: {host_localhost__44904: 'http://localhost:44904/'}
rosversion: '1.12.16

  '
run_id: e061a390-2374-11eb-aada-04d4c44c7d06
